### PR TITLE
Merge with UniversalMediaServer/master

### PR DESCRIPTION
**Pull request by Nadahar**
@WolfganP I created this PR so it's easy for you to get UniversalMediaServer/UniversalMediaServer#737 ready for merging. If you merge this PR, your PR should be ready to merge into UMS.

[Review on Reviewable](https://reviewable.io/reviews/wolfganp/universalmediaserver/1)

### CODE REVIEW

**Comment by Nadahar** [comment]
@WolfganP You need to merge this by clicking on the "merge" button so this is "synced" with the current UMS master.

**Comment by WolfganP** [comment]
Thanks @Nadahar but I usually test on my PC standalone via UMS-builder (easier for small testing since I lost my previous dev environment). Thx again!

**Comment by Nadahar** [comment]
@WolfganP The point is that if you want to merge your PR into UMS, @SubJunk wanted you to "sync merge" the PR with the latest UMS. I did that for you in this PR. 

If you merge these changes into this PR #1, your UMS PR UniversalMediaServer/UniversalMediaServer#737 will be updated with the latest UMS changes, so that we can merge it.

**Comment by WolfganP** [comment]
Ohh, I see now. Thx for the heads up. I totally forgot about that PR (several months went by and I didn't notice it wasn't merged). Thanks again!

**Pull request merged**
